# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

  [[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 45

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 50

  [[main]]
  name = "Talks"
  url = "#talks"
  weight = 55

[[main]]
  name = "Newsletter"
  url = "/newsletter"
  weight = 60

[[main]]
  name = "Podcast"
  url = "https://thenewprofessor.com/"
  weight = 65

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "https://cv.ryanstraight.com/"
  weight = 80

# Menu items for the different classes so they can look like the Academic Documentation
# https://github.com/sourcethemes/academic-www/blob/master/config/_default/menus.toml and
# https://raw.githubusercontent.com/sourcethemes/academic-www/master/content/docs/customization.md
# 302 class


