
# Why Podcast? {#why}

Why do we podcast? What would drive an otherwise sane person to voluntarily tumble down this rabbit hole?
Chances are, if you’re even reading this, you’ve already decided to try this thing out. While you may not be able to vocalize it specifically, you probably already know your *why.* Just in case, here are some reasons why you might consider podcasting in academic settings.

## It’s All About Learning
You can’t run a podcast without doing some preparation. Often times, that preparation comes in the format of *research*: learn something new, share it with the masses. 

## Storytelling
Perhaps you’re less interested in sharing research and novel ideas than you are in telling stories, be that your own or others’. This comes in many forms, from stories of perseverance and the struggles of individuals to reach their goals, to sharing stories of successful practice from other practitioners, whatever that may look like in your setting.

## Competencies
It takes a lot of skill to podcast. If your job focuses on fostering skills in *others* (you’re an instructor or a trainer, for example), helping others podcast is a great option. Students that learn to podcast develop the production skills while recording, technical skills when editing and hosting, “public” speaking skills when scripting or engaging in discussions, and even learn about satellite topics like copyright and fair use when determining just what they can use in their podcasts. Possibly the most important benefit that can come from podcasting is making...

## Connections
To demonstrate the benefits of the connections that are made in the process of podcasting, the facilitators of the *And We’re Live!* workshop share their brief thoughts below:

###	Carmen King de Ramrez: World Languages 21
When we decided to start this podcast, my co-host and I were both junior faculty in a relatively new field of applied linguistics. We wanted to interview our colleagues who were doing amazing work in that same field but weren't being noticed by more traditional WL scholars. Furthermore, we knew from our own experiences, that academic conferences are cost-prohibitive and often don't allow less established faculty to engage in in-depth conversation with more senior scholars. Our hope is that this podcast will bridge some of the scholarly dissemination and communication gaps that exist in academia.

### Kelvin Thompson and Jon Pizzo: TOPcast

###	John Stewart: OLC Live
OLC Live was born from the basic premise that one of the best parts of any conference is the conversation in the hallways. The virtual audience for OLC conferences or any conference, usually can’t participate in these informal Q&A’s, post-session debriefings, and conference networking. OLC Live has sought to bring both featured speakers and conference attendees into a forum where they could recap their conference experience and then talk to our online audience. Additionally, we take our viewers on tours of the conference, showing them what’s going on in the exhibit hall and the conference hotel more broadly.   

###	Ryan Straight: The New Professor
When I brought TNP back for a third season this fall semester, I decided to change formats and begin having guests on. Not interviews, per se, but just conversations about what they do, how they do it, and how others can benefit from their work. I’ve learned an incredible amount from them and my listeners have echoed that. I’ve made friends I don’t think I would have made, otherwise. It’s been wonderful.

###	Angela Gunder: The Innovation Labcast
Like all good things, the Innovation Labcast was a complete and total accident.  Ben Scragg, Dave Goodrich and I had just finished setting up the very first Innovation Lab for OLC Innovate, and were joined by friends in a latenight gabfest.  Ben turned on a mic and we all though “Huh. We should do this on the regular.”  Though much of podcasting is about planning, the beauty of it is that it has the power to capture extemporaneous musings and unseen connections lying just below the surface.
