# Plan {#plan}

How to begin to begin your podcast. Like most ventures, you'll find that the more thought you give to the idea up front, the more success you'll see upon launch. That said, it's unlikely you'll have the same exact podcast a year later so be open to evolving and updating, changing, and improving as time goes on.

## Theme

What's it about? It may be easy to look at this in a sort of Instructional Design lens and break it down into constitutive components to consider:

### The Subject

Basically, what is it? There's a delicate balance between choosing a topic that's broad enough to entice new listeners with just a look at the title and description, while keeping the subject narrow enough to find your own little niche that's truly *yours*. This is much harder than it sounds and where all that brainstorming comes in handiest.

Just to get those gears turning, here are some ideas for podcasting in an academic setting:

+ Talk about your research and its public impact
+ Building a sense of community among students and faculty
+ Podcasting about student podcasting
+ Discuss teaching, learning, and pedagogy with other faculty or staff
+ “Humanize” faculty by having candid, casual conversations
+ Start a podcast that covers a common reader
+ Publicize or support different initiatives at your institution or in the community
+ Advice for special groups of students, such as grad students, transfer students, or veterans


### The Context

Before you begin this rather time-consuming and energy-heavy adventure, where does it live, conceptually? Not the website, necessarily, but rather is it part of your current job? Are you doing it for fun? How segregated must you keep it from other aspects of your personal or professional life? 

### The Mode

Are you ranting on your own or interviewing guests? Each comes with their own set of complications and considerations. For example, if you're on your own you have much more flexibility in terms of timing and the publication rate, not to mention the content. If you're interviewing people or having conversations, you'll need to consider their schedules, complications that arise with distance, letting go of complete creative control since you can't *really* determine what they'll say, you'll need to learn to roll with that. The upside to this method is the obvious extra reach you'll start seeing as the draw is no longer just you but them, as well.

### The Audience

This is less about who you think will enjoy it (obviously everyone will, right?) and more about who you want to target. Some of us target all of higher education while some focus more on researchers, some on teachers, some even on students. If your target reach is too broad you end up pleasing no one but if the scope is too narrow that broad interest gets lost. This aspect is tied fairly neatly to the Subject choice as the two go hand-in-hand.

### The Outcomes

Why are you doing it? What do you want your listeners to get out of it? Do you want them to become highly engaged with you and the pod or do you just want them to enjoy and learn something? Are you selling something and want to point listeners to that or are you simply magnanimous and feel like sharing your knowledge with the world? Likewise, what are *you* trying to accomplish with the podcast? Do you want to keep it small or are you interested in growing it as large as it can get? This is related to finding your co-conspirators, if necessary (see below).

### The Assessment

How do you know if you're successful? Are you planning on simply using listening statistics from iTunes and Stitcher or are you gauging it by social media interaction on Twitter and Facebook? Is your main metric reviews and how hard are you willing to hustle to get those reviews? If you're connecting this to your job, have you discussed with your supervisor how to determine if you're actually fulfilling whatever requirement this ostensibly fulfills? Consider this a goal more than a metric and work toward it consistently. 

## Audience analysis

As mentioned above, knowing your audience is important. You don't want to try selling water to a drowning man, as the saying goes. It's key to plan early with whom you're hoping to connect. Identify, connect, and repeat.

## Lining up episodes

It's a good idea to line up (read: script or schedule, depending on your format) a number of episodes before actually launching your podcast, *especially* if you're choosing an intense or frequent schedule. Life happens and one of the absolutely key aspects of a successful podcast is *consistency* in your releases. If you say you're a weekly podcast and you go a month with no releases your subscribers will either a) unsubscribe because you're MIA and junking up their podcatcher, or b) just not come back.

As this is focused on “academic” podcasting, it’s a good idea to have a talk with your supervisor and/or the legal team if you want to have students on the pod. You may also need to discuss branding and name usage with the marketing team if you’re tying the pod directly to your work and, by extension, the institution.

## Finding your “partners in crime” (if any)
“I’ll have co-hosts!” Sounds like a great idea until your schedules conflict. Remember, while a podcast might seem like fun, it’s very much a business venture more than recreation. If you conceptualize and market your podcast a two-person show and have a hard time getting those two people together with ease, you’re going to have a bad time. If you do want to have co-hosts, one way to get around it is to have rotating hosts. This is great because it means you’re doing half the work as the pod bounces back and forth between you each episode. However, remember that the editing, the show posting, the notes, the format, everything still needs to be consistent. While having a partner in crime can make for an amazing podcast experience for listeners, be absolutely sure you can keep it up!
