# Publicize {#publicize}

You're almost done! Now, how do you get people to listen to your pod?

## Podcatchers
Podcatcher are the apps and services listeners use to receive your content as it’s released. While you’ll always have a few people going to your website to listen to it there, the vast majority of podcast listeners use their mobile devices, which means you’ve got some work to do beyond just posting your episode on your website.

While there are dozens of popular podcatching apps and distribution networks out there, you can really focus on the biggest and most popular ones: Stitcher, iTunes (now Apple Podcasts), Spotify, and Google Play Music. Each of these have particular and very specific requirements for inclusion of your podcast. This is where knowing your feed (above) comes in handy. You need to make sure your feed is formatted in such a way that these distribution networks can actually read it! Hosting services typically do this for you, as outlined above, but if you’re self-hosting you’ve got more work to do. This is dependent entirely on your hosting choice, so you’ll need to dig into their manual or support.

Beyond the podcatchers that you intend to use, there are countless other web services that scour Apple Podcasts or other services and re-list podcasts. Search engines may then index these ancillary podcatchers and list them in search results. See [this sample Google search results screen](https://c1.staticflickr.com/5/4836/45899166501_fd514f6253_b.jpg) in which four of the top nine search results for a podcast are from such ancillary podcatchers! For that matter, search engine optimization (SEO) of podcast websites is a whole other topic for consideration in promoting your podcast. For now, suffice it to say that having a website, while an additional management task, can pay off dividends as a value-add listener resource for show notes, listener comments, etc.

A word to the wise: read the requirements of networks like Stitcher and Apple Podcasts very, very closely, as failing to meet them will result in your podcast being rejected or delayed in publication. Also, your first couple weeks are often the most important, analytics-wise, so be sure you’ve got a few episodes to publish when you link up with these services and, of course, start heavily using...

## Social Media
Beyond your recordings, this is how you find and talk to your audience. And beyond merely *announcing* each new episode, consider how your social media account can add value to your audience. Perhaps you can drip-tweet resources from your show notes, or perhaps you might provide some behind-the-scenes photos or other information that listeners will enjoy. Also, if your podcast hosts a guest or if you mention people or organizations on an episode, tag those individuals on social media. This may be appreciated by those mentioned and might garner repostings of your original message. (Pro Tip: Make sure such postings inlude a clear path back to a specific episode or to your podcast’s website.)

Before you release your podcast, be sure you’ve established your social media accounts, included your graphic assets (profile photo, et cetera), linked to and back from your hosting site, and you’re ready to start engaging. Since you don’t want your podcasting idea to turn into a side job as a social media manager, many podcasters choose to use services like HootSuite, Buffer, or even IFTTT to automate much of their social media usage. This does not make up for one-on-one engagement, however! As your podcast (on Twitter, for instance), follow pods you feel are inspiration or professionally relevant. So, that might be following your own department, the university, and the guests you have on. It’s difficult starting out as it can feel you’re doing a lot of work and nobody’s listening but if you just keep at it, your audience will grow. Make it interesting and people will listen.

## Listener Engagement
Podcasting can feel like a one-sided relationship. Podcast listeners may feel very engaged cognitively and emotionally with a podcast and yet feel no obligation to connect with those producing the podcast. Actively reaching out to your listeners can let you know who is listening and can result in some valuable word-of-mouth promotion of your podcast. This might involve asking for listener input on topics/format, giving opportunities for listeners to “win” something, inviting listeners to real time online or in-person meet-and-greet events, and more. Even the simplest of outreach efforts will take a degree of planning and will require patience. The time from your making an “ask” on a podcast episode until a listener hears your offer and then eventually decides to take action can be much longer than you might expect. Not all listeners play your episode on the day it releases. Thus, any engagement campaign should allow for a slow motion response. However, be clear about your (realistic) due dates and don’t be shy about repeating offers for two or three episodes until the due date arrives. Then follow-up on a subsequent episode with a mention of the outcome from the campaign. For instance, perhaps you asked for listeners to vote between two possible new podcast logos. Announce the winning logo and direct listener attention to how they can see the new logo. Even the simplest of giveaways (e.g., a logo sticker for one’s personal device) can produce an email message with a mailing address from a listener. Such listener responses should be treated respectfully and as personally as possible. In this age of digital copy-and-paste communications, a brief handwritten note in response to an emailed address can go a long way to cultivating a long-term listener. Use your imagination. Just treat listeners humanely as valued partners. (Your podcast is nothing without them!)


## Institutional Buy-In
One quick way to get your audience growing and increase engagement is simply to get institutional buy-in. If you’re working with your department or can get approval and support from your institution, you’d be amazed what a couple retweets from them can do for your Twitter engagement, for example. Again, there tends to be red tape when you go this route, so making these connections earlier rather than later is important. If you do decide to go for buy-in at that level, be sure to ask about what kind of creative control you will still maintain and just how much of your content can be dictated by the institution, especially if you’re using their name, assets, or services.

## Work Your Network
Don’t be afraid to ask influential people in your network to listen to and write a brief testimonial about your podcast. Such a testimonial can go on your website, but it will do far more good if you can direct these generous thought leaders to post their comments on Apple Podcasts. You can get double-duty out of these recommendations if you periodically read one within a podcast episode. Existing listeners will hear that leaders within your community have positive things to say about your podcast, and those who are quoted will enjoy hearing their name promoted on your podcast. If a written recommendation is too big an “ask,” don’t hesitate to ask colleagues and listeners to visit Apple Podcasts and click a star rating. (Both recommendations and ratings help will help your podcast appear in Apple Podcasts’ recommendation engine.)

## Go Forth and Podcast!
That’s it! That’s pretty much everything you need to know to get your very own podcast off the ground. It’s a lot of work but, as virtually every podcaster will tell you, it’s absolutely worth it. Try to keep it fun, do something you’re passionate about, and tell a story. People will listen.
